require: rubocop-rspec

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/ClassLength:
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/ExampleLength:
  Max: 8

RSpec/NestedGroups:
  Max: 4
